//---<@
const portfolioObjects = [
	{
		img:"/assets/img/user.png",
		title:"User Directiory",
		description:"This is a User directory application that pulls data from an random data set API and return the information in rows. Then you can search by name in the users and you will find the searched person.",
		urlDemo:"https://mclarke9k9.github.io/myapp/",
		urlCode:"https://github.com/MClarke9k9/myapp",
		details:["Bootstrap","Javascript","Nodejs","ReactJS","Express","Heroku",],
	},
	{
		img:"/assets/img/substrak.png",
		title:"Subtrack",
		description:"",
		urlDemo:"https://glacial-shore-36326.herokuapp.com/",
		urlCode:"https://github.com/MClarke9k9/",
		details:["Materialize","ReactJS","Nodejs","MVC","Express","MySQL","Sequelize","Heroku"],
	},
	{
		img:"/assets/img/PORTFO.png",
		title:"My Portfolio!",
		description:".",
		urlDemo:"http://marksweetportfolio.herokuapp.com/",
		urlCode:"https://github.com/MClarke9k9/MCPortfolio",
		details:["Bootstrap","MongoDB","ExpressJS","ReactJS","NodeJS","Heroku"],
	},
	{
		img:"/assets/img/burger.jpg",
		title:"HavaBurger",
		description:".",
		urlDemo:"https://fast-retreat-55192.herokuapp.com/",
		urlCode:"https://github.com/MClarke9k9/Hava-Burger",
		details:["Materialize","Handlebars","Nodejs","MVC","Express","JQuery","ORM","Sequelize","Heroku"],
	},
	{
		img:"/assets/img/learn.png",
		title:"Learn Javascript",
		description:".",
		urlDemo:"https://mclarke9k9.github.io/Learn-Javascript/",
		urlCode:"https://github.com/MClarke9k9/Learn-Javascript",
		details:["Bootstrap","CSS3","DOM Manipulation","Javascript","jQuery",],
	},
	{
		img:"/assets/img/ecom.png",
		title:"EcomWebsite Mock-up",
		description:".",
		urlDemo:"https://mclarke9k9.github.io/EcomWebsite/",
		urlCode:"https://github.com/MClarke9k9/EcomWebsite",
		details:["Bootstrap","CSS3","Javascript","JQuery",],
	},
	{
		img:"/assets/img/wether.jpg",
		title:"WeatherDashboard!",
		description:".",
		urlDemo:"https://mclarke9k9.github.io/MyWeatherDashboard/",
		urlCode:"https://github.com/MClarke9k9/MyWeatherDashboard",
		details:["Bootstrap","CSS3","Javascript","AJAX","jQuery",],
	},
	{
		img:"/assets/img/planner.png",
		title:"DayPlanner",
		description:".",
		urlDemo:"https://mclarke9k9.github.io/YourDayPlanner/",
		urlCode:"https://github.com/MClarke9k9/YourDayPlanner",
		details:["Bootstrap","CSS3","DOM Manipulation","Javascript","jQuery","Momentjs",],
	},
	{
		img:"/assets/img/fb.jpg",
		title:"FacebookAudienceFinder",
		description:".",
		urlDemo:"https://modernmediamichael.github.io/firstproject/",
		urlCode:"https://github.com/modernmediamichael/firstproject",
		details:["Bootstrap","CSS3","DOM Manipulation","Javascript","jQuery",],
	},
	{
		img:"/assets/img/password.png",
		title:"PasswordGenerator",
		description:".",
		urlDemo:"https://mclarke9k9.github.io/PasswordGenerator/",
		urlCode:"https://github.com/MClarke9k9/PasswordGenerator",
		details:["HTML","CSS3","Javascript",],
	},
	
]

module.exports = portfolioObjects;