//---<@
const portfolioObjects = [
	{
		img:"/assets/img/user.png",
		title:"User Directiory",
		description:"This is a User directory application that pulls data from an random data set API and return the information in rows. Then you can search by name in the users and you will find the searched person.",
		urlDemo:"https://mclarke9k9.github.io/myapp/",
		urlCode:"https://github.com/MClarke9k9/myapp",
		details:["Bootstrap","Javascript","Nodejs","ReactJS","Express","Heroku",],
	},
	{
		img:"/assets/img/substrak.png",
		title:"Subtrack",
		description:"This applications intention was to help people keep track of their subscriptions along with how much it was costing them per month to help them with their budgeting.",
		urlDemo:"https://glacial-shore-36326.herokuapp.com/",
		urlCode:"https://github.com/MClarke9k9/",
		details:["Materialize","ReactJS","Nodejs","MVC","Express","MySQL","Sequelize","Heroku"],
	},
	{
		img:"/assets/img/PORTFO.jpg",
		title:"My Portfolio!",
		description:"Creating the Portfolio Cards to display my projects by using an object based approach for the information to append to each card along with Reacts component wrapping to display in their own section.",
		urlDemo:"http://marksweetportfolio.herokuapp.com/",
		urlCode:"https://github.com/MClarke9k9/MCPortfolio",
		details:["Bootstrap","MongoDB","ExpressJS","ReactJS","NodeJS","Heroku"],
	},
	{
		img:"/assets/img/burger.jpg",
		title:"HavaBurger",
		description:"The app will store every burger in a database, whether devoured or not.",
		urlDemo:"https://fast-retreat-55192.herokuapp.com/",
		urlCode:"https://github.com/MClarke9k9/Hava-Burger",
		details:["Materialize","Handlebars","Nodejs","MVC","Express","JQuery","ORM","Sequelize","Heroku"],
	},
	{
		img:"/assets/img/learn.png",
		title:"Learn Javascript",
		description:"With this timed Javascript test you will be able to test your on javascript while being time to further hone your skills!",
		urlDemo:"https://mclarke9k9.github.io/Learn-Javascript/",
		urlCode:"https://github.com/MClarke9k9/Learn-Javascript",
		details:["Bootstrap","CSS3","DOM Manipulation","Javascript","jQuery",],
	},
	{
		img:"/assets/img/ecom.png",
		title:"EcomWebsite Mock-up",
		description:"This is a EcomWebsite Mock-up I created while trying to learn how to use Sliders and make good looking landing pages",
		urlDemo:"https://mclarke9k9.github.io/EcomWebsite/",
		urlCode:"https://github.com/MClarke9k9/EcomWebsite",
		details:["Bootstrap","CSS3","Javascript","JQuery",],
	},
	{
		img:"/assets/img/wether.jpg",
		title:"WeatherDashboard!",
		description:"You as traveler might want to see the weather outlook for multiple cities, so that I can plan a trips accordingly.",
		urlDemo:"https://mclarke9k9.github.io/MyWeatherDashboard/",
		urlCode:"https://github.com/MClarke9k9/MyWeatherDashboard",
		details:["Bootstrap","CSS3","Javascript","AJAX","jQuery",],
	},
	{
		img:"/assets/img/planner.png",
		title:"DayPlanner",
		description:"Introduction As an myself employee with a busy schedule I wanted to add important events to a daily planner so that I can manage my time effectively, and this is the app I created to do just that.",
		urlDemo:"https://mclarke9k9.github.io/YourDayPlanner/",
		urlCode:"https://github.com/MClarke9k9/YourDayPlanner",
		details:["Bootstrap","CSS3","DOM Manipulation","Javascript","jQuery","Momentjs",],
	},
	{
		img:"/assets/img/fb.jpg",
		title:"FacebookAudienceFinder",
		description:"This is a Facebook Marketing Keyword Finder app that gives you the audience number per word given to help cut marketing keyword cost.",
		urlDemo:"https://modernmediamichael.github.io/firstproject/",
		urlCode:"https://github.com/modernmediamichael/firstproject",
		details:["Bootstrap","CSS3","DOM Manipulation","Javascript","jQuery",],
	},
	{
		img:"/assets/img/password.png",
		title:"PasswordGenerator",
		description:"I understand companies deal with sensitive data day in and day out. I wanted create a randomly generated a password that can meet the specific criteria so that you can create a strong password that provides greater security for your company.",
		urlDemo:"https://mclarke9k9.github.io/PasswordGenerator/",
		urlCode:"https://github.com/MClarke9k9/PasswordGenerator",
		details:["HTML","CSS3","Javascript",],
	},
	
]

module.exports = portfolioObjects;